del libace32.a
del libace64.a
del libbz2.a
del libexpat.a
del libgtcgi.a
del libgtgui.a
del libgtpca.a
del libgtstd.a
del libgtwin.a
del libgtwvg.a
del libgtwvt.a
del libharbour-32.a
del libhbamf.a
del libhbblat.a
del libhbblink.a
del libhbbz2.a
del libhbbz2io.a
del libhbcomio.a
del libhbcomm.a
del libhbcommon.a
del libhbcpage.a
del libhbcplr.a
del libhbct.a
del libhbcurl.a
del libhbcurls.a
del libhbdebug.a
del libhbexpat.a
del libhbextern.a
del libhbfimage.a
del libhbformat.a
del libhbfoxpro.a
del libhbfship.a
del libhbgt.a
del libhbgzio.a
del libhbhpdf.a
del libhbhsx.a
del libhbhttpd.a
del libhblang.a
del libhblzf.a
del libhbmacro.a
del libhbmaindllh.a
del libhbmaindllp.a
del libhbmainstd.a
del libhbmainwin.a
del libhbmemio.a
del libhbmisc.a
del libhbmlzo.a
del libhbmxml.a
del libhbmzip.a
del libhbnetio.a
del libhbnf.a
del libhbnortl.a
del libhbnulrdd.a
del libhbodbc.a
del libhboslib.a
del libhbpcre.a
del libhbpipeio.a
del libhbpp.a
del libhbrdd.a
del libhbrtl.a
del libhbsix.a
del libhbsms.a
del libhbsqlit3.a
del libhbtcpio.a
del libhbtest.a
del libhbtinymt.a
del libhbtip.a
del libhbtpathy.a
del libhbuddall.a
del libhbusrrdd.a
del libhbvm.a
del libhbvmmt.a
del libhbwin.a
del libhbxdiff.a
del libhbxpp.a
del libhbzebra.a
del libhbziparc.a
del libhbzlib.a
del libjpeg.a
del liblibhpdf.a
del liblzf.a
del libminilzo.a
del libminizip.a
del libmxml.a
del libpng.a
del librddads.a
del librddbm.a
del librddcdx.a
del librddfpt.a
del librddnsx.a
del librddntx.a
del librddsql.a
del libsddodbc.a
del libsddsqlt3.a
del libsqlite3.a
del libtinymt.a
del libunicows.a
del libxdiff.a
del libxhb.a
rem outras contribs
del libhbsvg.a
del libhbxlsxml.a
del libhbyaml.a
del librddado.a
del librddmisc.a
del libsqlrddpp.a

