del libace32.a
del libace64.a
del libbmdbfcdx.a
del libbmsixcdx.a
del libcodepage.a
del libcommon.a
del libcompiler.a
del libct.a
del libdbfcdx.a
del libdbffpt.a
del libdbfmdx.a
del libdbfnsx.a
del libdbfntx.a
del libdebug.a
del libdllmain.a
del libfilemem.a
del libfilib.a
del libgdlib.a
del libgtcgi.a
del libgtgui.a
del libgtpca.a
del libgtstd.a
del libgtwin.a
del libgtwvg.a
del libgtwvt.a
del libgtwvw.a
del libhbbtree.a
del libhbbz2.a
del libhbcab.a
del libhbcc.a
del libhbcgi.a
del libhbcomm.a
del libhbcurl.a
del libhbexpat.a
del libhbhpdf.a
del libhblzf.a
del libhbmlzo.a
del libhbmxml.a
del libhbmzip.a
del libhbodbc.a
del libhbsix.a
del libhbsqlit3.a
del libhbssl.a
del libhbtinymt.a
del libhbxdiff.a
del libhbzebra.a
del libhbzip.a
del libhsx.a
del libjpeg.a
del libang.a
del liblibharu.a
del liblibmisc.a
del liblibnf.a
del libacro.a
del libmysql.a
del libnulsys.a
del libpcrepos.a
del libpdflite.a
del libpng.a
del libpp.a
del librdd.a
del librddads.a
del librdds.a
del librddsql.a
del libredbfcdx.a
del libredbffpt.a
del librtl.a
del libsddmy.a
del libsddodbc.a
del libsddsqlt3.a
del libsevenzip.a
del libsixapi.a
del libsixcdx.a
del libtiff.a
del libtip.a
del libtipssl.a
del libuse_dll.a
del libusrrdd.a
del libvm.a
del libvmmt.a
del libxwt.a
del libzlib.a
del libfi_lib.a
del liblang.a
del libmacro.a
