cd lib\gc64
copy libbmdbfcdx.a \temp
copy libbmsixcdx.a \temp
copy libcodepage.a \temp
copy libcommon.a \temp
copy libcompiler.a \temp
copy libct.a \temp
copy libdbfcdx.a \temp
copy libdbffpt.a \temp
copy libdbfmdx.a \temp
copy libdbfnsx.a \temp
copy libdbfntx.a \temp
copy libdebug.a \temp
copy libdllmain.a \temp
copy libfilemem.a \temp
copy libfi_copy lib.a \temp
copy libgdcopy lib.a \temp
copy libhbbtree.a \temp
copy libhbcab.a \temp
copy libhbcc.a \temp
copy libhbcgi.a \temp
copy libhbssl.a \temp
copy libhbzip.a \temp
copy libhsx.a \temp
copy liblang.a \temp
copy liblibcrypto64.a \temp
copy liblibcurl64.a \temp
copy liblibharu.a \temp
copy liblibmisc.a \temp
copy liblibmysql64.a \temp
copy liblibnf.a \temp
copy liblibssl64.a \temp
copy libmacro.a \temp
copy libmysql.a \temp
copy libnulsys.a \temp
copy libpcrepos.a \temp
copy libpdflite.a \temp
copy libpp.a \temp
copy librdd.a \temp
copy librdds.a \temp
copy libredbfcdx.a \temp
copy libredbffpt.a \temp
copy librtl.a \temp
copy libsddmy.a \temp
copy libsevenzip.a \temp
copy libsixapi.a \temp
copy libsixcdx.a \temp
copy libtiff.a \temp
copy libtip.a \temp
copy libtipssl.a \temp
copy libuse_dll.a \temp
copy libusrrdd.a \temp
copy libvm.a \temp
copy libvmmt.a \temp
copy libxwt.a \temp
copy libzcopy lib.a \temp
