MDI(" Ý Ajuste Dipam ")
aRETU := PERFEC( { "MM06" }, { "M6" }, { "MM96" } )
cARQUIVO := aRETU[ 5, 1 ]
IF ! USEREDE(ALLTRIM(cARQUIVO),1,99)
   RETU
ENDIF
IF ! USEREDE("MD04",1,99)
   DBCLOSEALL()
   RETU .F.
ENDIF
DBSELECTAR(ALLTRIM(cARQUIVO))
DBGOTOP()
WHILE ! EOF()
   @ 24,60 SAY NUMERO
   IF EMPTY(DIPAM)
      nINDICE:=2
      mDOPER:=DCFONEW
      IF EMPTY(mDOPER)
         mDOPER:=DOPER
         nINDICE=3
      ENDIF
      DBSELECTAR("MD04")
      DBSETORDER(nINDICE)
      DBGOTOP()
      DBSEEK(mDOPER)
      mDIPAM:=IF(FOUND(),DIPAM,"  ")
      DBSELECTAR(ALLTRIM(cARQUIVO))
      IF ! EMPTY(mDIPAM)
         NETGRVCAM("DIPAM",mDIPAM)
      ENDIF
   ENDIF
   DBSKIP()
ENDDO
DBCLOSEAREA()
