*
* m_adic -> Registros Iniciais DIPI
*
*
*

function M_adic
PARA wMADIC,lOPEN,lDIPI
IF VALTYPE(lOPEN)#"L"
   lOPEN:=.T.
ENDIF
IF VALTYPE(lDIPI)#"L"
   lDIPI:=.F.
ENDIF
mORDEM:=IF(wMADIC=1,ULTIMOREG(ARQWORK4,"ORDEM"),mNUMERO)
IF wMADIC=1
   mORDEM++
ENDIF
xORDEM:=mORDEM
xBUSCA:=IF(wMADIC=1,STR(mNRNOTA,8)+STR(mFORNECEDO,5),STR(mNUMERO,8))
xCOUNT:=1
IF lOPEN
   WHILE ! USEREDE(ARQWORK2,1,1)
   ENDDO
   WHILE ! USEREDE(ARQWORK4,1,99)
   ENDDO
ENDIF
DBSELECTAR(ARQWORK2)
DBGOTOP()
DBSEEK(xBUSCA)
WHILE xBUSCA=IF(wMADIC=1,STR(NRNOTA,8)+STR(FORNECEDO,5),STR(NUMERO,8)).AND.! EOF()
   IF wMADIC=1
      mNUMERO:=NRNOTA
      mITEM  :=ITEM
   ENDIF
   IF wMADIC=2
      mITEM  :=SEQ
      IF EMPTY(mITEM)
         mITEM:=xCOUNT
         xCOUNT++
      ENDIF
      mDATAREF:=mDATA
   ENDIF
   mTIPOFOR  := mTIPOCLI
   mDCFONEW  := mCFONEW
   mSUBDOPER := mSUBOPER
   IF TIPOENT="B"
      IF ! EMPTY(mCFONEWB)
         mDCFONEW:=mCFONEWB
      ENDIF
   ENDIF
   mCONSUMO  := CONSUMO
   mDBASEICM := BASEICM
   mDICM     := ICM
   mDVALICM  := VALORICM
   mDBASEIPI := BASEIPI
   mDIPI     := IPI
   mDVALIPI  := VALORIPI
   mDCLASSIPI:= CLASSIPI
   mDVALORNF := VALORTOT
   mUNIDADE  := UNID
   mQUANT    := QTDE
   mDIPIPI   := DIPIPI
   mDIPICM   := DIPICM
   mDPISCON  := PISCON
   mDOPER:=""
   mDIPAM:=""
   IF lOPEN
      mDOPER:=OBTER("MD04",mDCFONEW,"CFO",2)
      mDIPAM:=OBTER("MD04",mDCFONEW,"DIPAM",2)
      IF lDIPI
        mDIPIPI:=OBTER("MD04",mDCFONEW,"DIPIPI",2)
        mDIPICM:=OBTER("MD04",mDCFONEW,"DIPICM",2)
      ENDIF
   ELSE
      DBSELECTAR("MD04")
      DBGOTOP()
      IF DBSEEK(mDCFONEW)
         mDOPER:=CFO
         mDIPAM:=DIPAM
         IF lDIPI
            mDIPIPI   := DIPIPI
            mDIPICM   := DIPICM
         ENDIF
      ENDIF
   ENDIF
   DBSELECTAR(ARQWORK2)
   mISENTAIPI:= 0
   mOUTRAIPI := 0
   mOUTRAICM := 0
   mISENTAICM:= 0
   mCHKIPI:=""
   IF ! EMPTY(mDIPICM)
      netgrvcam("DIPICM",mDIPICM)
   ENDIF
   IF ! EMPTY(mDIPIPI)
      netgrvcam("DIPIPI",mDIPIPI)
   ENDIF
   IF EMPTY(IPI)
      IF DIPIPI="I"
         mDBASEIPI=0
         mISENTAIPI=VALORTOT
      ENDIF
      IF DIPIPI="O"
         mDBASEIPI=0
         mOUTRAIPI=VALORTOT
      ENDIF
   ENDIF
   IF EMPTY(ICM)
      IF DIPICM="I"
         mDBASEICM=0
         mISENTAICM=VALORTOT
      ENDIF
      IF DIPICM="O"
         mDBASEICM=0
         mOUTRAICM=VALORTOT
      ENDIF
   ENDIF
   IF ! EMPTY(ICM).AND.VALORTOT>BASEICM
      mDBASEICM=BASEICM
      IF DIPICM="R"
         mISENTAICM =VALORMER-BASEICM
         mCHKIPI:="R"
      ENDIF
      IF DIPICM="O"
         mOUTRAICM =VALORTOT-BASEICM
      ENDIF
      IF DIPICM="I"
         mISENTAICM=VALORTOT-BASEICM
      ENDIF
   ENDIF
   IF ! EMPTY(IPI).AND.VALORTOT>BASEIPI
      mDBASEIPI=BASEIPI
      IF DIPIPI="O"
         mOUTRAIPI =VALORTOT-BASEIPI
      ENDIF
      IF DIPIPI="I"
         mISENTAIPI=VALORTOT-BASEIPI
      ENDIF
   ENDIF
   mPULASIN:=" "
   IF mDVALORNF<0.00 //desconto nf manuaus e outros descontos
      mPULASIN:="S"
   ENDIF
   IF TIPOENT="X"
      cTMPCOD=ALLTRIM(CODIGO)
      IF cTMPCOD="SEGURO".OR.cTMPCOD="PISCONFINS" ;
         .OR.cTMPCOD="COMPLEMENTO".OR.cTMPCOD="NAOTRIBUTADO" .OR.cTMPCOD="ACESSORIAS"
         mPULASIN:="S"
      ENDIF
   ENDIF
   NOVOOPA(ARQWORK4,.T.)
   DBSELECTAR(ARQWORK2)
   DBSKIP()
ENDDO
IF lOPEN
   DBSELECTAR(ARQWORK2)
   DBCLOSEAREA()
   DBSELECTAR(ARQWORK4)
   DBCLOSEAREA()
ENDIF
